### ISSUE TITLE
Error During Prepare

### ISSUE THREAD

**Issue by ryan-clancy** [osirrc/ielab-docker#3]
When running the `jig`, we pass in the root directory for `disk45` (see [here](https://github.com/osirrc/jig/issues/28)). For example, running `python run.py prepare --repo osirrc2019/ielab --collections robust04=/home/ryan/sync/ir/collections/disk45=trectext` gives:

```
cat: /input/collections/robust04/disk4: Is a directory
{"error":{"root_cause":[{"type":"parse_exception","reason":"request body is required"}],"type":"parse_exception","reason":"request body is required"},"status":400}
cat: /input/collections/robust04/disk5: Is a directory
{"error":{"root_cause":[{"type":"parse_exception","reason":"request body is required"}],"type":"parse_exception","reason":"request body is required"},"status":400}
```

Even pointing to more specific directories (i.e., the `disk4` folder) seems to have similar errors.

Can this image be updated so that it works pointing to the root `disk45` directory? Can you provide the commands you used for testing in the README?

**Comment by hscells** [comment]
I think we can close this now.
